// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articleTagFieldNames          = builder.RawFieldNames(&ArticleTag{}, true)
	articleTagRows                = strings.Join(articleTagFieldNames, ",")
	articleTagRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(articleTagFieldNames, "id", "create_time"))

	cachePublicArticleTagIdPrefix = "cache:public:articleTag:id:"
)

type (
	articleTagModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ArticleTag) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ArticleTag, error)
		Update(ctx context.Context, session sqlx.Session, data *ArticleTag) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultArticleTagModel struct {
		sqlc.CachedConn
		table string
	}

	ArticleTag struct {
		Id         int64     `db:"id"`          // 文章标签id
		ArticleId  int64     `db:"article_id"`  // 文章id
		TagId      int64     `db:"tag_id"`      // 标签id
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 修改时间
	}
)

func newArticleTagModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultArticleTagModel {
	return &defaultArticleTagModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."article_tag"`,
	}
}

func (m *defaultArticleTagModel) Insert(ctx context.Context, session sqlx.Session, data *ArticleTag) (sql.Result, error) {
	query, args, err := sq.Insert(m.table).Columns(articleTagRows).Values(data.Id, data.ArticleId, data.TagId, data.CreateTime, data.UpdateTime).
		PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return nil, err
	}
	publicArticleTagIdKey := fmt.Sprintf("%s%v", cachePublicArticleTagIdPrefix, data.Id)

	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicArticleTagIdKey)
	return ret, err
}

func (m *defaultArticleTagModel) FindOne(ctx context.Context, id int64) (*ArticleTag, error) {
	publicArticleTagIdKey := fmt.Sprintf("%s%v", cachePublicArticleTagIdPrefix, id)
	var resp ArticleTag
	err := m.QueryRowCtx(ctx, &resp, publicArticleTagIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", articleTagRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleTagModel) Update(ctx context.Context, session sqlx.Session, data *ArticleTag) error {
	publicArticleTagIdKey := fmt.Sprintf("%s%v", cachePublicArticleTagIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, articleTagRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.ArticleId, data.TagId, time.Now())

		}
		return conn.ExecCtx(ctx, query, data.Id, data.ArticleId, data.TagId, time.Now())
	}, publicArticleTagIdKey)
	return err
}

func (m *defaultArticleTagModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query, args, err := sq.Delete(m.table).Where(sq.Eq{"id": id}).PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return err
	}
	publicArticleTagIdKey := fmt.Sprintf("%s%v", cachePublicArticleTagIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicArticleTagIdKey)
	return err
}

func (m *defaultArticleTagModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicArticleTagIdPrefix, primary)
}

func (m *defaultArticleTagModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", articleTagRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultArticleTagModel) tableName() string {
	return m.table
}
