// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bizTagsFieldNames          = builder.RawFieldNames(&BizTags{}, true)
	bizTagsRows                = strings.Join(bizTagsFieldNames, ",")
	bizTagsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(bizTagsFieldNames, "id", "create_time"))

	cachePublicBizTagsIdPrefix = "cache:public:bizTags:id:"
)

type (
	bizTagsModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *BizTags) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BizTags, error)
		Update(ctx context.Context, session sqlx.Session, data *BizTags) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultBizTagsModel struct {
		sqlc.CachedConn
		table string
	}

	BizTags struct {
		Id          int64     `db:"id"`
		Name        string    `db:"name"`        // 书签名
		Description string    `db:"description"` // 描述
		CreateTime  time.Time `db:"create_time"` // 添加时间
		UpdateTime  time.Time `db:"update_time"` // 更新时间
	}
)

func newBizTagsModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultBizTagsModel {
	return &defaultBizTagsModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."biz_tags"`,
	}
}

func (m *defaultBizTagsModel) Insert(ctx context.Context, session sqlx.Session, data *BizTags) (sql.Result, error) {
	query, args, err := sq.Insert(m.table).Columns(bizTagsRows).Values(data.Id, data.Name, data.Description, data.CreateTime, data.UpdateTime).
		PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return nil, err
	}
	publicBizTagsIdKey := fmt.Sprintf("%s%v", cachePublicBizTagsIdPrefix, data.Id)

	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicBizTagsIdKey)
	return ret, err
}

func (m *defaultBizTagsModel) FindOne(ctx context.Context, id int64) (*BizTags, error) {
	publicBizTagsIdKey := fmt.Sprintf("%s%v", cachePublicBizTagsIdPrefix, id)
	var resp BizTags
	err := m.QueryRowCtx(ctx, &resp, publicBizTagsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", bizTagsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBizTagsModel) Update(ctx context.Context, session sqlx.Session, data *BizTags) error {
	publicBizTagsIdKey := fmt.Sprintf("%s%v", cachePublicBizTagsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, bizTagsRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.Name, data.Description, time.Now())

		}
		return conn.ExecCtx(ctx, query, data.Id, data.Name, data.Description, time.Now())
	}, publicBizTagsIdKey)
	return err
}

func (m *defaultBizTagsModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query, args, err := sq.Delete(m.table).Where(sq.Eq{"id": id}).PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return err
	}
	publicBizTagsIdKey := fmt.Sprintf("%s%v", cachePublicBizTagsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicBizTagsIdKey)
	return err
}

func (m *defaultBizTagsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicBizTagsIdPrefix, primary)
}

func (m *defaultBizTagsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", bizTagsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBizTagsModel) tableName() string {
	return m.table
}
