// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bizArticleTagsFieldNames          = builder.RawFieldNames(&BizArticleTags{}, true)
	bizArticleTagsRows                = strings.Join(bizArticleTagsFieldNames, ",")
	bizArticleTagsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(bizArticleTagsFieldNames, "id", "create_time"))

	cachePublicBizArticleTagsIdPrefix = "cache:public:bizArticleTags:id:"
)

type (
	bizArticleTagsModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *BizArticleTags) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BizArticleTags, error)
		Update(ctx context.Context, session sqlx.Session, data *BizArticleTags) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultBizArticleTagsModel struct {
		sqlc.CachedConn
		table string
	}

	BizArticleTags struct {
		Id         int64     `db:"id"`
		TagId      int64     `db:"tag_id"`      // 标签表主键
		ArticleId  int64     `db:"article_id"`  // 文章ID
		CreateTime time.Time `db:"create_time"` // 添加时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newBizArticleTagsModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultBizArticleTagsModel {
	return &defaultBizArticleTagsModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."biz_article_tags"`,
	}
}

func (m *defaultBizArticleTagsModel) Insert(ctx context.Context, session sqlx.Session, data *BizArticleTags) (sql.Result, error) {
	query, args, err := sq.Insert(m.table).Columns(bizArticleTagsRows).Values(data.Id, data.TagId, data.ArticleId, data.CreateTime, data.UpdateTime).
		PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return nil, err
	}
	publicBizArticleTagsIdKey := fmt.Sprintf("%s%v", cachePublicBizArticleTagsIdPrefix, data.Id)

	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicBizArticleTagsIdKey)
	return ret, err
}

func (m *defaultBizArticleTagsModel) FindOne(ctx context.Context, id int64) (*BizArticleTags, error) {
	publicBizArticleTagsIdKey := fmt.Sprintf("%s%v", cachePublicBizArticleTagsIdPrefix, id)
	var resp BizArticleTags
	err := m.QueryRowCtx(ctx, &resp, publicBizArticleTagsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", bizArticleTagsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBizArticleTagsModel) Update(ctx context.Context, session sqlx.Session, data *BizArticleTags) error {
	publicBizArticleTagsIdKey := fmt.Sprintf("%s%v", cachePublicBizArticleTagsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, bizArticleTagsRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.TagId, data.ArticleId, time.Now())

		}
		return conn.ExecCtx(ctx, query, data.Id, data.TagId, data.ArticleId, time.Now())
	}, publicBizArticleTagsIdKey)
	return err
}

func (m *defaultBizArticleTagsModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query, args, err := sq.Delete(m.table).Where(sq.Eq{"id": id}).PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return err
	}
	publicBizArticleTagsIdKey := fmt.Sprintf("%s%v", cachePublicBizArticleTagsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicBizArticleTagsIdKey)
	return err
}

func (m *defaultBizArticleTagsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicBizArticleTagsIdPrefix, primary)
}

func (m *defaultBizArticleTagsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", bizArticleTagsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBizArticleTagsModel) tableName() string {
	return m.table
}
