// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	discussFieldNames          = builder.RawFieldNames(&Discuss{}, true)
	discussRows                = strings.Join(discussFieldNames, ",")
	discussRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(discussFieldNames, "id", "create_time"))

	cachePublicDiscussIdPrefix = "cache:public:discuss:id:"
)

type (
	discussModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Discuss) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Discuss, error)
		Update(ctx context.Context, session sqlx.Session, data *Discuss) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultDiscussModel struct {
		sqlc.CachedConn
		table string
	}

	Discuss struct {
		Id         int64     `db:"id"`          // 评论id
		Uid        int64     `db:"uid"`         // 发表用户
		ArticleId  int64     `db:"article_id"`  // 文章id
		Content    string    `db:"content"`     // 评论内容
		LikeCount  int64     `db:"like_count"`  // 点赞数
		ParentId   int64     `db:"parent_id"`   // 父级评论id
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 修改时间
	}
)

func newDiscussModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultDiscussModel {
	return &defaultDiscussModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."discuss"`,
	}
}

func (m *defaultDiscussModel) Insert(ctx context.Context, session sqlx.Session, data *Discuss) (sql.Result, error) {
	query, args, err := sq.Insert(m.table).Columns(discussRows).Values(data.Id, data.Uid, data.ArticleId, data.Content, data.LikeCount, data.ParentId, data.CreateTime, data.UpdateTime).
		PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return nil, err
	}
	publicDiscussIdKey := fmt.Sprintf("%s%v", cachePublicDiscussIdPrefix, data.Id)

	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicDiscussIdKey)
	return ret, err
}

func (m *defaultDiscussModel) FindOne(ctx context.Context, id int64) (*Discuss, error) {
	publicDiscussIdKey := fmt.Sprintf("%s%v", cachePublicDiscussIdPrefix, id)
	var resp Discuss
	err := m.QueryRowCtx(ctx, &resp, publicDiscussIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", discussRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDiscussModel) Update(ctx context.Context, session sqlx.Session, data *Discuss) error {
	publicDiscussIdKey := fmt.Sprintf("%s%v", cachePublicDiscussIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, discussRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.Uid, data.ArticleId, data.Content, data.LikeCount, data.ParentId, time.Now())

		}
		return conn.ExecCtx(ctx, query, data.Id, data.Uid, data.ArticleId, data.Content, data.LikeCount, data.ParentId, time.Now())
	}, publicDiscussIdKey)
	return err
}

func (m *defaultDiscussModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query, args, err := sq.Delete(m.table).Where(sq.Eq{"id": id}).PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return err
	}
	publicDiscussIdKey := fmt.Sprintf("%s%v", cachePublicDiscussIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicDiscussIdKey)
	return err
}

func (m *defaultDiscussModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicDiscussIdPrefix, primary)
}

func (m *defaultDiscussModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", discussRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDiscussModel) tableName() string {
	return m.table
}
