// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysUpdateRecordeFieldNames          = builder.RawFieldNames(&SysUpdateRecorde{}, true)
	sysUpdateRecordeRows                = strings.Join(sysUpdateRecordeFieldNames, ",")
	sysUpdateRecordeRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysUpdateRecordeFieldNames, "id", "create_time"))

	cachePublicSysUpdateRecordeIdPrefix = "cache:public:sysUpdateRecorde:id:"
)

type (
	sysUpdateRecordeModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SysUpdateRecorde) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysUpdateRecorde, error)
		Update(ctx context.Context, session sqlx.Session, data *SysUpdateRecorde) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultSysUpdateRecordeModel struct {
		sqlc.CachedConn
		table string
	}

	SysUpdateRecorde struct {
		Id          int64     `db:"id"`
		Version     string    `db:"version"`      // 更新版本
		Description string    `db:"description"`  // 更新记录备注
		RecordeTime time.Time `db:"recorde_time"` // 项目更新时间
		CreateTime  time.Time `db:"create_time"`  // 添加时间
		UpdateTime  time.Time `db:"update_time"`  // 更新时间
	}
)

func newSysUpdateRecordeModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSysUpdateRecordeModel {
	return &defaultSysUpdateRecordeModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."sys_update_recorde"`,
	}
}

func (m *defaultSysUpdateRecordeModel) Insert(ctx context.Context, session sqlx.Session, data *SysUpdateRecorde) (sql.Result, error) {
	query, args, err := sq.Insert(m.table).Columns(sysUpdateRecordeRows).Values(data.Id, data.Version, data.Description, data.RecordeTime, data.CreateTime, data.UpdateTime).
		PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return nil, err
	}
	publicSysUpdateRecordeIdKey := fmt.Sprintf("%s%v", cachePublicSysUpdateRecordeIdPrefix, data.Id)

	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysUpdateRecordeIdKey)
	return ret, err
}

func (m *defaultSysUpdateRecordeModel) FindOne(ctx context.Context, id int64) (*SysUpdateRecorde, error) {
	publicSysUpdateRecordeIdKey := fmt.Sprintf("%s%v", cachePublicSysUpdateRecordeIdPrefix, id)
	var resp SysUpdateRecorde
	err := m.QueryRowCtx(ctx, &resp, publicSysUpdateRecordeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysUpdateRecordeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUpdateRecordeModel) Update(ctx context.Context, session sqlx.Session, data *SysUpdateRecorde) error {
	publicSysUpdateRecordeIdKey := fmt.Sprintf("%s%v", cachePublicSysUpdateRecordeIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysUpdateRecordeRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.Version, data.Description, data.RecordeTime, time.Now())

		}
		return conn.ExecCtx(ctx, query, data.Id, data.Version, data.Description, data.RecordeTime, time.Now())
	}, publicSysUpdateRecordeIdKey)
	return err
}

func (m *defaultSysUpdateRecordeModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query, args, err := sq.Delete(m.table).Where(sq.Eq{"id": id}).PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return err
	}
	publicSysUpdateRecordeIdKey := fmt.Sprintf("%s%v", cachePublicSysUpdateRecordeIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysUpdateRecordeIdKey)
	return err
}

func (m *defaultSysUpdateRecordeModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicSysUpdateRecordeIdPrefix, primary)
}

func (m *defaultSysUpdateRecordeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysUpdateRecordeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysUpdateRecordeModel) tableName() string {
	return m.table
}
