// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysNoticeFieldNames          = builder.RawFieldNames(&SysNotice{}, true)
	sysNoticeRows                = strings.Join(sysNoticeFieldNames, ",")
	sysNoticeRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysNoticeFieldNames, "id", "create_time"))

	cachePublicSysNoticeIdPrefix = "cache:public:sysNotice:id:"
)

type (
	sysNoticeModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SysNotice) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysNotice, error)
		Update(ctx context.Context, session sqlx.Session, data *SysNotice) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultSysNoticeModel struct {
		sqlc.CachedConn
		table string
	}

	SysNotice struct {
		Id         int64     `db:"id"`
		UserId     int64     `db:"user_id"`     // 被通知的用户ID
		Status     string    `db:"status"`      // 通知状态
		Title      string    `db:"title"`       // 通知的标题
		Content    string    `db:"content"`     // 通知的内容
		CreateTime time.Time `db:"create_time"` // 添加时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newSysNoticeModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSysNoticeModel {
	return &defaultSysNoticeModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."sys_notice"`,
	}
}

func (m *defaultSysNoticeModel) Insert(ctx context.Context, session sqlx.Session, data *SysNotice) (sql.Result, error) {
	query, args, err := sq.Insert(m.table).Columns(sysNoticeRows).Values(data.Id, data.UserId, data.Status, data.Title, data.Content, data.CreateTime, data.UpdateTime).
		PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return nil, err
	}
	publicSysNoticeIdKey := fmt.Sprintf("%s%v", cachePublicSysNoticeIdPrefix, data.Id)

	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysNoticeIdKey)
	return ret, err
}

func (m *defaultSysNoticeModel) FindOne(ctx context.Context, id int64) (*SysNotice, error) {
	publicSysNoticeIdKey := fmt.Sprintf("%s%v", cachePublicSysNoticeIdPrefix, id)
	var resp SysNotice
	err := m.QueryRowCtx(ctx, &resp, publicSysNoticeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysNoticeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysNoticeModel) Update(ctx context.Context, session sqlx.Session, data *SysNotice) error {
	publicSysNoticeIdKey := fmt.Sprintf("%s%v", cachePublicSysNoticeIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysNoticeRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.UserId, data.Status, data.Title, data.Content, time.Now())

		}
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Status, data.Title, data.Content, time.Now())
	}, publicSysNoticeIdKey)
	return err
}

func (m *defaultSysNoticeModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query, args, err := sq.Delete(m.table).Where(sq.Eq{"id": id}).PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return err
	}
	publicSysNoticeIdKey := fmt.Sprintf("%s%v", cachePublicSysNoticeIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysNoticeIdKey)
	return err
}

func (m *defaultSysNoticeModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicSysNoticeIdPrefix, primary)
}

func (m *defaultSysNoticeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysNoticeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysNoticeModel) tableName() string {
	return m.table
}
