// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysResourcesFieldNames          = builder.RawFieldNames(&SysResources{}, true)
	sysResourcesRows                = strings.Join(sysResourcesFieldNames, ",")
	sysResourcesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysResourcesFieldNames, "id", "create_time"))

	cachePublicSysResourcesIdPrefix = "cache:public:sysResources:id:"
)

type (
	sysResourcesModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SysResources) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysResources, error)
		Update(ctx context.Context, session sqlx.Session, data *SysResources) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultSysResourcesModel struct {
		sqlc.CachedConn
		table string
	}

	SysResources struct {
		Id         int64     `db:"id"`
		Name       string    `db:"name"`
		Tp         string    `db:"tp"`
		Url        string    `db:"url"`
		Permission string    `db:"permission"`
		ParentId   int64     `db:"parent_id"`
		Sort       int64     `db:"sort"`
		External   int64     `db:"external"` // 是否外部链接
		Available  int64     `db:"available"`
		Icon       string    `db:"icon"`        // 菜单图标
		CreateTime time.Time `db:"create_time"` // 添加时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newSysResourcesModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSysResourcesModel {
	return &defaultSysResourcesModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."sys_resources"`,
	}
}

func (m *defaultSysResourcesModel) Insert(ctx context.Context, session sqlx.Session, data *SysResources) (sql.Result, error) {
	query, args, err := sq.Insert(m.table).Columns(sysResourcesRows).Values(data.Id, data.Name, data.Tp, data.Url, data.Permission, data.ParentId, data.Sort, data.External, data.Available, data.Icon, data.CreateTime, data.UpdateTime).
		PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return nil, err
	}
	publicSysResourcesIdKey := fmt.Sprintf("%s%v", cachePublicSysResourcesIdPrefix, data.Id)

	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysResourcesIdKey)
	return ret, err
}

func (m *defaultSysResourcesModel) FindOne(ctx context.Context, id int64) (*SysResources, error) {
	publicSysResourcesIdKey := fmt.Sprintf("%s%v", cachePublicSysResourcesIdPrefix, id)
	var resp SysResources
	err := m.QueryRowCtx(ctx, &resp, publicSysResourcesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysResourcesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysResourcesModel) Update(ctx context.Context, session sqlx.Session, data *SysResources) error {
	publicSysResourcesIdKey := fmt.Sprintf("%s%v", cachePublicSysResourcesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysResourcesRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.Name, data.Tp, data.Url, data.Permission, data.ParentId, data.Sort, data.External, data.Available, data.Icon, time.Now())

		}
		return conn.ExecCtx(ctx, query, data.Id, data.Name, data.Tp, data.Url, data.Permission, data.ParentId, data.Sort, data.External, data.Available, data.Icon, time.Now())
	}, publicSysResourcesIdKey)
	return err
}

func (m *defaultSysResourcesModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query, args, err := sq.Delete(m.table).Where(sq.Eq{"id": id}).PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return err
	}
	publicSysResourcesIdKey := fmt.Sprintf("%s%v", cachePublicSysResourcesIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysResourcesIdKey)
	return err
}

func (m *defaultSysResourcesModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicSysResourcesIdPrefix, primary)
}

func (m *defaultSysResourcesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysResourcesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysResourcesModel) tableName() string {
	return m.table
}
