// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysUserRoleFieldNames          = builder.RawFieldNames(&SysUserRole{}, true)
	sysUserRoleRows                = strings.Join(sysUserRoleFieldNames, ",")
	sysUserRoleRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysUserRoleFieldNames, "id", "create_time"))

	cachePublicSysUserRoleIdPrefix = "cache:public:sysUserRole:id:"
)

type (
	sysUserRoleModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SysUserRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysUserRole, error)
		Update(ctx context.Context, session sqlx.Session, data *SysUserRole) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultSysUserRoleModel struct {
		sqlc.CachedConn
		table string
	}

	SysUserRole struct {
		Id         int64     `db:"id"`
		UserId     int64     `db:"user_id"`
		RoleId     int64     `db:"role_id"`
		CreateTime time.Time `db:"create_time"` // 添加时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newSysUserRoleModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSysUserRoleModel {
	return &defaultSysUserRoleModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."sys_user_role"`,
	}
}

func (m *defaultSysUserRoleModel) Insert(ctx context.Context, session sqlx.Session, data *SysUserRole) (sql.Result, error) {
	query, args, err := sq.Insert(m.table).Columns(sysUserRoleRows).Values(data.Id, data.UserId, data.RoleId, data.CreateTime, data.UpdateTime).
		PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return nil, err
	}
	publicSysUserRoleIdKey := fmt.Sprintf("%s%v", cachePublicSysUserRoleIdPrefix, data.Id)

	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysUserRoleIdKey)
	return ret, err
}

func (m *defaultSysUserRoleModel) FindOne(ctx context.Context, id int64) (*SysUserRole, error) {
	publicSysUserRoleIdKey := fmt.Sprintf("%s%v", cachePublicSysUserRoleIdPrefix, id)
	var resp SysUserRole
	err := m.QueryRowCtx(ctx, &resp, publicSysUserRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysUserRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserRoleModel) Update(ctx context.Context, session sqlx.Session, data *SysUserRole) error {
	publicSysUserRoleIdKey := fmt.Sprintf("%s%v", cachePublicSysUserRoleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysUserRoleRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.UserId, data.RoleId, time.Now())

		}
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.RoleId, time.Now())
	}, publicSysUserRoleIdKey)
	return err
}

func (m *defaultSysUserRoleModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query, args, err := sq.Delete(m.table).Where(sq.Eq{"id": id}).PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return err
	}
	publicSysUserRoleIdKey := fmt.Sprintf("%s%v", cachePublicSysUserRoleIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysUserRoleIdKey)
	return err
}

func (m *defaultSysUserRoleModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicSysUserRoleIdPrefix, primary)
}

func (m *defaultSysUserRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysUserRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysUserRoleModel) tableName() string {
	return m.table
}
