// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysRoleResourcesFieldNames          = builder.RawFieldNames(&SysRoleResources{}, true)
	sysRoleResourcesRows                = strings.Join(sysRoleResourcesFieldNames, ",")
	sysRoleResourcesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysRoleResourcesFieldNames, "id", "create_time"))

	cachePublicSysRoleResourcesIdPrefix = "cache:public:sysRoleResources:id:"
)

type (
	sysRoleResourcesModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SysRoleResources) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysRoleResources, error)
		Update(ctx context.Context, session sqlx.Session, data *SysRoleResources) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultSysRoleResourcesModel struct {
		sqlc.CachedConn
		table string
	}

	SysRoleResources struct {
		Id          int64     `db:"id"`
		RoleId      int64     `db:"role_id"`
		ResourcesId int64     `db:"resources_id"`
		CreateTime  time.Time `db:"create_time"` // 添加时间
		UpdateTime  time.Time `db:"update_time"` // 更新时间
	}
)

func newSysRoleResourcesModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSysRoleResourcesModel {
	return &defaultSysRoleResourcesModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."sys_role_resources"`,
	}
}

func (m *defaultSysRoleResourcesModel) Insert(ctx context.Context, session sqlx.Session, data *SysRoleResources) (sql.Result, error) {
	query, args, err := sq.Insert(m.table).Columns(sysRoleResourcesRows).Values(data.Id, data.RoleId, data.ResourcesId, data.CreateTime, data.UpdateTime).
		PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return nil, err
	}
	publicSysRoleResourcesIdKey := fmt.Sprintf("%s%v", cachePublicSysRoleResourcesIdPrefix, data.Id)

	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysRoleResourcesIdKey)
	return ret, err
}

func (m *defaultSysRoleResourcesModel) FindOne(ctx context.Context, id int64) (*SysRoleResources, error) {
	publicSysRoleResourcesIdKey := fmt.Sprintf("%s%v", cachePublicSysRoleResourcesIdPrefix, id)
	var resp SysRoleResources
	err := m.QueryRowCtx(ctx, &resp, publicSysRoleResourcesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysRoleResourcesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRoleResourcesModel) Update(ctx context.Context, session sqlx.Session, data *SysRoleResources) error {
	publicSysRoleResourcesIdKey := fmt.Sprintf("%s%v", cachePublicSysRoleResourcesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysRoleResourcesRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.RoleId, data.ResourcesId, time.Now())

		}
		return conn.ExecCtx(ctx, query, data.Id, data.RoleId, data.ResourcesId, time.Now())
	}, publicSysRoleResourcesIdKey)
	return err
}

func (m *defaultSysRoleResourcesModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query, args, err := sq.Delete(m.table).Where(sq.Eq{"id": id}).PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return err
	}
	publicSysRoleResourcesIdKey := fmt.Sprintf("%s%v", cachePublicSysRoleResourcesIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysRoleResourcesIdKey)
	return err
}

func (m *defaultSysRoleResourcesModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicSysRoleResourcesIdPrefix, primary)
}

func (m *defaultSysRoleResourcesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysRoleResourcesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysRoleResourcesModel) tableName() string {
	return m.table
}
