// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysConfigFieldNames          = builder.RawFieldNames(&SysConfig{}, true)
	sysConfigRows                = strings.Join(sysConfigFieldNames, ",")
	sysConfigRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysConfigFieldNames, "id", "create_time"))

	cachePublicSysConfigIdPrefix = "cache:public:sysConfig:id:"
)

type (
	sysConfigModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SysConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysConfig, error)
		Update(ctx context.Context, session sqlx.Session, data *SysConfig) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultSysConfigModel struct {
		sqlc.CachedConn
		table string
	}

	SysConfig struct {
		Id          int64     `db:"id"`
		ConfigKey   string    `db:"config_key"`   // 配置关键字
		ConfigValue string    `db:"config_value"` // 配置项内容
		CreateTime  time.Time `db:"create_time"`  // 添加时间
		UpdateTime  time.Time `db:"update_time"`  // 更新时间
	}
)

func newSysConfigModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSysConfigModel {
	return &defaultSysConfigModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."sys_config"`,
	}
}

func (m *defaultSysConfigModel) Insert(ctx context.Context, session sqlx.Session, data *SysConfig) (sql.Result, error) {
	query, args, err := sq.Insert(m.table).Columns(sysConfigRows).Values(data.Id, data.ConfigKey, data.ConfigValue, data.CreateTime, data.UpdateTime).
		PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return nil, err
	}
	publicSysConfigIdKey := fmt.Sprintf("%s%v", cachePublicSysConfigIdPrefix, data.Id)

	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysConfigIdKey)
	return ret, err
}

func (m *defaultSysConfigModel) FindOne(ctx context.Context, id int64) (*SysConfig, error) {
	publicSysConfigIdKey := fmt.Sprintf("%s%v", cachePublicSysConfigIdPrefix, id)
	var resp SysConfig
	err := m.QueryRowCtx(ctx, &resp, publicSysConfigIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysConfigModel) Update(ctx context.Context, session sqlx.Session, data *SysConfig) error {
	publicSysConfigIdKey := fmt.Sprintf("%s%v", cachePublicSysConfigIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysConfigRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.ConfigKey, data.ConfigValue, time.Now())

		}
		return conn.ExecCtx(ctx, query, data.Id, data.ConfigKey, data.ConfigValue, time.Now())
	}, publicSysConfigIdKey)
	return err
}

func (m *defaultSysConfigModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query, args, err := sq.Delete(m.table).Where(sq.Eq{"id": id}).PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return err
	}
	publicSysConfigIdKey := fmt.Sprintf("%s%v", cachePublicSysConfigIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysConfigIdKey)
	return err
}

func (m *defaultSysConfigModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicSysConfigIdPrefix, primary)
}

func (m *defaultSysConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysConfigModel) tableName() string {
	return m.table
}
