// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysRoleFieldNames          = builder.RawFieldNames(&SysRole{}, true)
	sysRoleRows                = strings.Join(sysRoleFieldNames, ",")
	sysRoleRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysRoleFieldNames, "id", "create_time"))

	cachePublicSysRoleIdPrefix = "cache:public:sysRole:id:"
)

type (
	sysRoleModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SysRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysRole, error)
		Update(ctx context.Context, session sqlx.Session, data *SysRole) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultSysRoleModel struct {
		sqlc.CachedConn
		table string
	}

	SysRole struct {
		Id          int64     `db:"id"`
		Name        string    `db:"name"` // 角色名
		Description string    `db:"description"`
		Available   int64     `db:"available"`
		CreateTime  time.Time `db:"create_time"` // 添加时间
		UpdateTime  time.Time `db:"update_time"` // 更新时间
	}
)

func newSysRoleModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSysRoleModel {
	return &defaultSysRoleModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."sys_role"`,
	}
}

func (m *defaultSysRoleModel) Insert(ctx context.Context, session sqlx.Session, data *SysRole) (sql.Result, error) {
	query, args, err := sq.Insert(m.table).Columns(sysRoleRows).Values(data.Id, data.Name, data.Description, data.Available, data.CreateTime, data.UpdateTime).
		PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return nil, err
	}
	publicSysRoleIdKey := fmt.Sprintf("%s%v", cachePublicSysRoleIdPrefix, data.Id)

	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysRoleIdKey)
	return ret, err
}

func (m *defaultSysRoleModel) FindOne(ctx context.Context, id int64) (*SysRole, error) {
	publicSysRoleIdKey := fmt.Sprintf("%s%v", cachePublicSysRoleIdPrefix, id)
	var resp SysRole
	err := m.QueryRowCtx(ctx, &resp, publicSysRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRoleModel) Update(ctx context.Context, session sqlx.Session, data *SysRole) error {
	publicSysRoleIdKey := fmt.Sprintf("%s%v", cachePublicSysRoleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysRoleRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.Name, data.Description, data.Available, time.Now())

		}
		return conn.ExecCtx(ctx, query, data.Id, data.Name, data.Description, data.Available, time.Now())
	}, publicSysRoleIdKey)
	return err
}

func (m *defaultSysRoleModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query, args, err := sq.Delete(m.table).Where(sq.Eq{"id": id}).PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return err
	}
	publicSysRoleIdKey := fmt.Sprintf("%s%v", cachePublicSysRoleIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysRoleIdKey)
	return err
}

func (m *defaultSysRoleModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicSysRoleIdPrefix, primary)
}

func (m *defaultSysRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysRoleModel) tableName() string {
	return m.table
}
