// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysTemplateFieldNames          = builder.RawFieldNames(&SysTemplate{}, true)
	sysTemplateRows                = strings.Join(sysTemplateFieldNames, ",")
	sysTemplateRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysTemplateFieldNames, "id", "create_time"))

	cachePublicSysTemplateIdPrefix = "cache:public:sysTemplate:id:"
)

type (
	sysTemplateModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SysTemplate) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysTemplate, error)
		Update(ctx context.Context, session sqlx.Session, data *SysTemplate) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultSysTemplateModel struct {
		sqlc.CachedConn
		table string
	}

	SysTemplate struct {
		Id         int64     `db:"id"`
		RefKey     string    `db:"ref_key"`     // 键
		RefValue   string    `db:"ref_value"`   // 模板内容
		CreateTime time.Time `db:"create_time"` // 添加时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newSysTemplateModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSysTemplateModel {
	return &defaultSysTemplateModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."sys_template"`,
	}
}

func (m *defaultSysTemplateModel) Insert(ctx context.Context, session sqlx.Session, data *SysTemplate) (sql.Result, error) {
	query, args, err := sq.Insert(m.table).Columns(sysTemplateRows).Values(data.Id, data.RefKey, data.RefValue, data.CreateTime, data.UpdateTime).
		PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return nil, err
	}
	publicSysTemplateIdKey := fmt.Sprintf("%s%v", cachePublicSysTemplateIdPrefix, data.Id)

	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysTemplateIdKey)
	return ret, err
}

func (m *defaultSysTemplateModel) FindOne(ctx context.Context, id int64) (*SysTemplate, error) {
	publicSysTemplateIdKey := fmt.Sprintf("%s%v", cachePublicSysTemplateIdPrefix, id)
	var resp SysTemplate
	err := m.QueryRowCtx(ctx, &resp, publicSysTemplateIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysTemplateRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysTemplateModel) Update(ctx context.Context, session sqlx.Session, data *SysTemplate) error {
	publicSysTemplateIdKey := fmt.Sprintf("%s%v", cachePublicSysTemplateIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysTemplateRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.RefKey, data.RefValue, time.Now())

		}
		return conn.ExecCtx(ctx, query, data.Id, data.RefKey, data.RefValue, time.Now())
	}, publicSysTemplateIdKey)
	return err
}

func (m *defaultSysTemplateModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query, args, err := sq.Delete(m.table).Where(sq.Eq{"id": id}).PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		return err
	}
	publicSysTemplateIdKey := fmt.Sprintf("%s%v", cachePublicSysTemplateIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, query, args...)
		}
		return conn.ExecCtx(ctx, query, args...)
	}, publicSysTemplateIdKey)
	return err
}

func (m *defaultSysTemplateModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicSysTemplateIdPrefix, primary)
}

func (m *defaultSysTemplateModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysTemplateRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysTemplateModel) tableName() string {
	return m.table
}
